<?php

namespace WBB\CoreBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function findTopCities()
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.onTopCity', $qb->expr()->literal(true)))
        ;

        return $qb->getQuery()->getResult();
    }

    public function findBarFinderCities()
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->orderBy($this->getAlias().'.onTopCity', 'DESC')
            ->addOrderBy($this->getAlias().'.name', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findCitiesWithBars($keyword = "")
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->innerJoin($this->getAlias().".bars", "b")
            ->leftJoin($this->getAlias().".country", "c")
            ->where($qb->expr()->like($this->getAlias().'.name', "'%".$keyword."%'"))
            ->orWhere($qb->expr()->like('c.name', "'%".$keyword."%'"))
        ;

        return $qb->getQuery()->getResult();
    }

    public function findByNameAndCountry($name = "", $country = null)
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->leftJoin($this->getAlias().".country", "c")
            ->where($qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal($name)))
            ->andWhere($qb->expr()->eq('c.id', $country->getId()))
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
} 