<?php

namespace WBB\CoreBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function findTopCities()
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.onTopCity', $qb->expr()->literal(true)))
        ;

        return $qb->getQuery()->getResult();
    }

    public function findCitiesWithBars()
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias().", COUNT(b) AS HIDDEN nbBars")
            ->innerJoin($this->getAlias().".bars", "b")
            ->having('nbBars > 0')
        ;

        return $qb->getQuery()->getResult();
    }
} 