<?php

namespace WBB\CoreBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function findCountriesOrderedByName($onlyQueryBuilder = false)
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->orderBy($this->getAlias().'.name', 'ASC')
        ;

        if($onlyQueryBuilder){
            return $qb;
        }else{
            return $qb->getQuery()->getResult();
        }
    }
} 