<?php

namespace WBB\CoreBundle\Repository;

/**
 * SuburbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuburbRepository extends EntityRepository
{
    public function findByCityWithBars($city)
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->innerJoin($this->getAlias().'.bars', 'b')
            ->where($qb->expr()->eq($this->getAlias().'.city', $city->getId()))
        ;

        return $qb->getQuery()->getResult();
    }
} 