<?php

namespace WBB\CoreBundle\Repository;

/**
 * SuburbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuburbRepository extends EntityRepository
{

} 