<?php

namespace WBB\CoreBundle\Repository;

/**
 * SuburbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuburbRepository extends EntityRepository
{
    public function findByCityWithBars($city)
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->innerJoin($this->getAlias().'.bars', 'b')
            ->where($qb->expr()->eq($this->getAlias().'.city', $city->getId()))
        ;

        return $qb->getQuery()->getResult();
    }

    public function findByNameAndCity($name = "", $city = null)
    {
        $qb = $this->createQuerybuilder($this->getAlias());
        $qb
            ->select($this->getAlias())
            ->leftJoin($this->getAlias().".city", "c")
            ->where($qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal($name)))
            ->andWhere($qb->expr()->eq('c.id', $city->getId()))
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
} 