<?php

namespace WBB\BarBundle\Repository;

use WBB\BarBundle\Entity\Ad;
use WBB\CoreBundle\Repository\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
    public function findOneByPositionAndCountry($position = Ad::WBB_ADS_HP_300x250, $country = null)
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.position', $qb->expr()->literal($position)))
            ->andWhere($qb->expr()->between($qb->expr()->literal(date('Y-m-d')), $this->getAlias().'.beginAt', $this->getAlias().'.endAt'))
            ->orderBy($this->getAlias().'.createdAt', 'DESC')
            ->setMaxResults(1);
        ;

        if($country){
            $qb
                ->leftJoin($this->getAlias().'.countries', 'c')
                ->andWhere($qb->expr()->eq($this->getAlias().'.country', $country->getId()))
            ;
        }

        return $qb->getQuery()->getResult();
    }
} 