<?php

namespace WBB\BarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarRepository extends EntityRepository
{

} 