<?php

namespace WBB\BarBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;
use WBB\BarBundle\Entity\Bar;

/**
 * BarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarTagRepository extends EntityRepository
{
    public function findYouMayAlsoLike(Bar $bar, $location, $exceptBars = null, $limit = 4)
    {
        $ids = array($bar->getId());
        if($exceptBars != null)
        {
            foreach($exceptBars as $exBar)
            {
                if($exBar)
                    $ids[] = $exBar->getId();
            }
        }

        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias().'.bar')
            ->innerjoin($this->getAlias().'.bar', 'b')
            ->innerjoin('b.city', 'c')
            ->innerjoin($this->getAlias().'.tag', 't')
            ->where($qb->expr()->eq('b.onTop', $qb->expr()->literal(true)))
            ->andWhere($qb->expr()->in('t.id',':tags'))
            ->andWhere($qb->expr()->notIn('b.id',':exceptBars'))
            ->setParameter('tags', $bar->getTagsIds())
            ->setParameter('exceptBars', $ids)
            ->setMaxResults($limit)
        ;

        if($location == BarRepository::BAR_LOCATION_CITY and !is_null($bar->getCity()))
        {
            $qb
                ->andWhere($qb->expr()->eq('b.city', ':city'))
                ->setParameter('city', $bar->getCity());
        }

        if($location == BarRepository::BAR_LOCATION_COUNTRY and !is_null($bar->getCity()) and !is_null($bar->getCity()->getCountry()))
        {
            $qb
                ->andWhere($qb->expr()->eq('c.country', ':country'))
                ->setParameter('country', $bar->getCity()->getCountry());
        }

        return $qb->getQuery()->getResult();
    }
} 