<?php

namespace WBB\BarBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * BestOfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestOfRepository extends EntityRepository
{
    public function findTopBestOfs($city = null, $favoris = null, $limit = null)
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.onTop', $qb->expr()->literal(true)))
            ->orderBy($this->getAlias().'.createdAt', 'DESC')
        ;

        if($city){
            $qb->andWhere($qb->expr()->eq($this->getAlias().'.city', $city->getId()));
        }

        if($limit){
            $qb->setMaxResults($limit);
        }

        // TODO: Favoris WBB

        return $qb->getQuery()->getResult();
    }
} 