<?php

namespace WBB\BarBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findLatestNews($city=null, $limit = 3)
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.isOnTop', $qb->expr()->literal(true)))
            ->orderBy($this->getAlias().'.createdAt', 'DESC')
            ->setMaxResults($limit)
        ;

        if($city){
            $qb
                ->leftJoin($this->getAlias().'.cities', 'c')
                ->andWhere($qb->expr()->eq('c.id', $city->getId()));
        }

        return $qb->getQuery()->getResult();
    }
} 