<?php

namespace WBB\BarBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findLatestNews()
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select("$this->getAlias()")
            ->where($qb->expr()->eq($this->getAlias().'.isOnTop', $qb->expr()->literal(true)))
            ->orderBy('createdAt', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }
} 