<?php

namespace WBB\BarBundle\Repository;

use WBB\BarBundle\Entity\Tag;
use WBB\CoreBundle\Repository\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findByType($type, $onlyQueryBuilder = false, $limit = 0, $name = null, $exacteName = true)
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.type', $type))
            ->orderBy($this->getAlias().'.name', 'ASC')
        ;

        if ($limit > 0) {
            $qb->setMaxResults($limit);
        }

        if ($name) {
            $nameValue = $name;
            if(!$exacteName)$nameValue.='%';
            $qb->andWhere($qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal($nameValue)));
        }

        if ($onlyQueryBuilder) {
            return $qb;
        } elseif ($limit == 1) {
            return $qb->getQuery()->getOneOrNullResult();
        } else {
            return $qb->getQuery()->getResult();
        }
    }

    public function findBarFinderMoods()
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias().'.name,'.$this->getAlias().'.id')
            ->where($qb->expr()->eq($this->getAlias().'.type', Tag::WBB_TAG_TYPE_ENERGY_LEVEL))
            ->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal('Chill out')) ,
                        $qb->expr()->orX(
                            $qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal('Party')),
                            $qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal('Casual'))
                    )
                )
            );

        return $qb->getQuery()->getArrayResult();

    }
}
