<?php

namespace WBB\BarBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findByType($type, $onlyQueryBuilder = false, $limit = 0, $name = null)
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.type', $type))
            ->orderBy($this->getAlias().'.name', 'ASC')
        ;

        if($limit > 0)
        {
            $qb->setMaxResults($limit);
        }

        if($name){
            $qb->andWhere($qb->expr()->like($this->getAlias().'.name', $qb->expr()->literal($name)));
        }

        return ($onlyQueryBuilder)? $qb : $qb->getQuery()->getResult();
    }
} 