<?php

namespace WBB\BarBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * TipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipRepository extends EntityRepository
{
    public function findLatestTips($offset = 0, $limit = 8)
    {
        $qb = $this->createQuerybuilder($this->getAlias());

        $qb
            ->select($this->getAlias())
            ->where($qb->expr()->eq($this->getAlias().'.status', 1))
            ->orderBy($this->getAlias().'.createdAt', 'DESC')
            ->setMaxResults($limit)
        ;

        if($offset > 0){
            $qb
                ->setFirstResult($offset);
        }

        return $qb->getQuery()->getResult();
    }
} 