<?php

namespace WBB\UserBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findAdminUsers()
    {
        $role = \FOS\UserBundle\Model\User::ROLE_SUPER_ADMIN;
        $qb = $this->createQueryBuilder('u')
                ->where('u.roles LIKE :roles')
                ->setParameter('roles', '%"' . $role . '"%');

        return $qb->getQuery()->getResult();
    }

}
