<?php

namespace WBB\UserBundle\Repository;

use WBB\CoreBundle\Repository\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}
